Allow for Browser Compatibility
ripple/ripple-binary-codec pull request #107
Opened 2020-10-21 00:29 UTC by natenichols

## High Level Overview of Change
This change makes it possible to run this in the browser

### Context of Change
With the packages we were using, nodeJS buffers would be compiled down to browser compatible buffers. These browser compatible buffers do not have the API for `readBigUInt64BE` and `writeBigUInt64BE`. This rewrite makes the binary-codec compatible with these tools.

### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

## Test Plan
No functionality was changed, all tests still pass.

2020-10-21 03:04 UTC, intelliot approved these changes
LGTM. I wonder if we should add a note in the README about browser compatibility? Since we use BigInt now, will it work in browsers that don't support BigInt?

All new browsers support it, but old ones do not, like Internet Explorer and Safari versions prior to Safari 14.

2020-10-21 14:33 UTC, natenichols commented
That would be correct. It will not work in Browsers w/o support for BigInt. How important is it that old browsers support `ripple-lib`? 

Since new browsers support it, I don't see a problem using BigInt. If we wanna make sure it is compatible with old Browsers we can use a library to replace BigInt.

2020-10-21 15:36 UTC, natenichols commented
> LGTM. I wonder if we should add a note in the README about browser compatibility? Since we use BigInt now, will it work in browsers that don't support BigInt?
> 
> All new browsers support it, but old ones do not, like Internet Explorer and Safari versions prior to Safari 14.

I added a short note about browser compatibility. I'm also debating whether to continue to update `v2.6` in order to support older browsers. All we would need to do to keep older versions up to date with the protocol is to update `definitions.json`. Thoughts?

2020-10-21 17:54 UTC, intelliot commented
I'm happy either way. I think the important thing is that we call out what the expected compatibility is, so that users are aware of which browsers are expected to work. If you'd like to update the [0.2.x branch](https://github.com/ripple/ripple-binary-codec/tree/0.2.x), I think that is reasonable, too (especially since it's not much work). On the other hand, it's also ok to wait until someone complains :) Maybe no one will complain.

2020-10-21 17:55 UTC, intelliot commented on README.md
> +`ripple-binary-codec` is compatible with Browsers that support `BigInt` types.
I think we should say that all new browsers support BigInt, but Internet Explorer and old Safari (versions prior to Safari 14) do not. I got this info from caniuse.com

2020-10-21 17:59 UTC, natenichols commented
> I'm happy either way. I think the important thing is that we call out what the expected compatibility is, so that users are aware of which browsers are expected to work. If you'd like to update the [0.2.x branch](https://github.com/ripple/ripple-binary-codec/tree/0.2.x), I think that is reasonable, too (especially since it's not much work). On the other hand, it's also ok to wait until someone complains :) Maybe no one will complain.

Sounds good to me.

2020-10-21 18:03 UTC, Stormtv commented
@natenichols 

BigInt only have 80% support atm I would recommend using https://www.npmjs.com/package/big-integer which acts as a polyfill for the 20% of users who don't have BigInt support.

2020-10-21 19:27 UTC, Stormtv approved these changes

2020-10-22 17:54 UTC, intelliot approved these changes

2020-10-22 17:55 UTC, intelliot requested changes

2020-10-22 17:55 UTC, intelliot commented on src/ledger-hashes.ts
> +    console.log(header.total_coins);
I think we should remove `console.log`s if everything is working

2020-10-22 20:12 UTC, intelliot approved these changes

2020-10-22 20:36 UTC, merged